Update concurrent_scanner.py
In Py3.x doing `dict.values()` returns a `dict_values` instance which does not allow index lookup. Have to convert it to a `list`

```python
>>> a = {'a':1, 'b':2}
>>> a.values()
dict_values([1, 2])
>>> a.values()[0]
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    a.values()[0]
TypeError: 'dict_values' object does not support indexing
>>> list(a.values())[0]
1
>>> 
```